//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea7_GuiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosdeta
    {
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public decimal PrecioUnidad { get; set; }
        public short Cantidad { get; set; }
        public double Descuento { get; set; }
    
        public virtual pedidoscabe pedidoscabe { get; set; }
        public virtual pedidoscabe pedidoscabe1 { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Productos Productos1 { get; set; }
    }
}
