select*from Cargos

DECLARE @CODIGO CHAR(3)='99';
DECLARE @PAIS VARCHAR(30) ='PERU';


MERGE PAISES AS TARGET
USING (SELECT @CODIGO,@PAIS) AS SOURCE(Idpais,NombrePais)
ON SOURCE.Idpais = TARGET.Idpais
WHEN MATCHED THEN
    UPDATE SET NombrePais=SOURCE.NombrePais
WHEN NOT MATCHED THEN
    INSERT (Idpais, NombrePais) 
	VALUES(SOURCE.Idpais,SOURCE.NombrePais);
select*from PAISES
	

	DECLARE @PRODUCTO VARCHAR (50), @ID INT 
    SET @PRODUCTO = 'VINO' SET @ID = 22

MERGE PRODUCTOS AS TARGET
USING (SELECT @PRODUCTO ,@ID) AS SOURCE (NOMBREPRODUCTO,IDPRODUCTO)
ON TARGET.IDPRODUCTO = SOURCE.IDPRODUCTO
WHEN MATCHED AND TARGET.UNIDADESENEXISTENCIA<=0 THEN
   DELETE 
WHEN  MATCHED THEN
  UPDATE SET NomProducto=SOURCE.NOMBREPRODUCTO;

  SELECT*FROM Productos