/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-15 21:03:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MenuUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<title>Menuy</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto|Open+Sans\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"> -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link href=\"Estilos/Index.css\" rel=\"stylesheet\" />\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"page-top\">\n");
      out.write("	<!-- header-bg -->\n");
      out.write("	<!-- Navigation-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/Nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Masthead-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Services-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/Servicios.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Portfolio Grid-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/portafolio.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- About-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/Carrusel.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Team-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/comentario.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Clients-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/contactos.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Contact-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/formComent.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Footer-->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragmetos/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Portfolio Modals-->\n");
      out.write("	<!-- Portfolio item 1 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Santuario Histórico de Machu\n");
      out.write("									Picchu</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">Cuzco</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/1.webp\" alt=\"...\" />\n");
      out.write("								<p>Es el mayor atractivo turístico del Perú y la máxima\n");
      out.write("									expresión de la arquitectura prehispánica en Sudamérica.\n");
      out.write("									Construida a finales del siglo XV por órdenes del inca\n");
      out.write("									Pachacutec, Machu Picchu es una ciudadela imponente, enclavada\n");
      out.write("									en una montaña de la selva alta. Considerada como una de las\n");
      out.write("									Siete Maravillas del Mundo Moderno, la “montaña vieja” (ese es\n");
      out.write("									su nombre en español) no solo es arqueología. La naturaleza\n");
      out.write("									aquí es prodigiosa y alberga una interesante diversidad de\n");
      out.write("									especies de flora y fauna. Estas le dan vida y hermosean un\n");
      out.write("									santuario boscoso a 2430 m s.n.m.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 2 horas</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.550</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio item 2 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Complejo Arqueológico Chan Chan</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">a 5 kilómetros de Trujillo\n");
      out.write("								</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/2.webp\" alt=\"...\" />\n");
      out.write("								<p>Una ciudad de barro con 9 templos amurallados con\n");
      out.write("									representaciones zoomorfas. Una urbe costera de 20 km² de\n");
      out.write("									extensión que, en su apogeo, albergó hasta 100 000 personas.\n");
      out.write("									Una obra arquitectónica que fue el centro del poder de los\n");
      out.write("									chimú (700 a 1400 d. C.), una civilización prehispánica del\n");
      out.write("									norte del Perú. Chan Chan (Sol Sol en español) es una evidencia\n");
      out.write("									arqueológica de que el desarrollo en el antiguo Perú, no se\n");
      out.write("									limita a la zona andina ni a la avanzada organización social,\n");
      out.write("									militar y agrícola del imperio incaico.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 2 horas</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.550</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio item 3 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Islas Ballestas</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">Pisco</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/3.webp\" alt=\"...\" />\n");
      out.write("								<p>El Perú no solo es pampas y cordilleras. Su costa\n");
      out.write("									desértica es el refugio de diversas especies de la fauna\n");
      out.write("									marina. Eso es lo que descubrirás en Ballesta, un conjunto de\n");
      out.write("									pequeñas islas frente a la península de Paracas (provincia de\n");
      out.write("									Pisco, región Ica). Tu aventura en el Pacífico peruano\n");
      out.write("									comenzará en el muelle artesanal El Chaco, donde zarpan las\n");
      out.write("									embarcaciones hacía Ballestas, donde avistarás —siempre desde\n");
      out.write("									el mar— colonias de lobos marinos y nutrias, además de\n");
      out.write("									pingüinos de Humboldt, pelícanos, cormoranes de patas rojas,\n");
      out.write("									zarcillos y piqueros, entre otras aves.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 1 horas</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.250</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio item 4 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Reserva Nacional Titicaca</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">Puno</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/4.webp\" alt=\"...\" />\n");
      out.write("								<p>Un lugar legendario con islas tejidas con totora, con\n");
      out.write("									playas que parecen extraídas del Caribe y comunidades\n");
      out.write("									organizadas para recibir a los turistas. Todo eso y mucho más\n");
      out.write("									en el lago Titicaca que en sus 8300 km² de extensión\n");
      out.write("									compartidos por Perú y Bolivia, alberga 530 especies acuáticas\n");
      out.write("									de flora y fauna.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 4 horas</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.150</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio item 5 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Líneas y geoglifos de Nazca</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">Ica</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/5.webp\" alt=\"...\" />\n");
      out.write("								<p>Uno de los mayores misterios arqueológicos del planeta se\n");
      out.write("									encuentra en el Perú. Diversas teorías —terrenales, cósmicas y\n");
      out.write("									hasta interplanetarias— tratan de explicar el origen de las\n");
      out.write("									líneas de Nazca, cuyos geoglifos representan seres\n");
      out.write("									antropomorfos, zoomorfos y fitomorfos, además de figuras\n");
      out.write("									geométricas trazadas en el siglo V a. C. en una pampa de 500\n");
      out.write("									km². Reconocidas como Patrimonio Cultural de la Humanidad por\n");
      out.write("									la Unesco en 1994, las enigmáticas líneas elaboradas por los\n");
      out.write("									hombres de la cultura nazca, solo se ven a plenitud desde el\n");
      out.write("									aire. Esta peculiaridad genera diversas interpretaciones\n");
      out.write("									científicas y místicas que generan un aura de misteriosa.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 2 horas</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.150</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio item 6 modal popup-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\"\n");
      out.write("		tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"close-modal\" data-bs-dismiss=\"modal\">\n");
      out.write("					<img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-8\">\n");
      out.write("							<div class=\"modal-body\">\n");
      out.write("								<!-- Project details-->\n");
      out.write("								<h2 class=\"text-uppercase\">Centro Histórico de Lima</h2>\n");
      out.write("								<p class=\"item-intro text-muted\">Lima</p>\n");
      out.write("								<img class=\"img-fluid d-block mx-auto\"\n");
      out.write("									src=\"assets/img/portfolio/6.webp\" alt=\"...\" />\n");
      out.write("								<p>Es un error turístico pensar que Lima es solo un lugar de\n");
      out.write("									paso. Fundada el 18 de enero de 1535 por el español Francisco\n");
      out.write("									Pizarro, la capital peruana conserva en su Centro Histórico,\n");
      out.write("									iglesias, casonas y conventos que son auténticas maravillas de\n");
      out.write("									la arquitectura colonial. Declarado Patrimonio Cultural de la\n");
      out.write("									Humidad por la Unesco en 1991, las calles de la vieja Lima te\n");
      out.write("									conducirán a espacios urbanos monumentales, como la plaza de\n");
      out.write("									Armas, la Catedral, el convento de San Francisco, el Palacio de\n");
      out.write("									Gobierno, el jirón de La Unión, entre otros lugares que te\n");
      out.write("									transportarán en el tiempo.</p>\n");
      out.write("								<ul class=\"list-inline\">\n");
      out.write("									<li><strong>Tiempo de viaje:</strong> 30 minutos</li>\n");
      out.write("									<li><strong>Costo:</strong> S/.50</li>\n");
      out.write("								</ul>\n");
      out.write("								<button class=\"btn btn-primary btn-xl text-uppercase\"\n");
      out.write("									data-bs-dismiss=\"modal\" type=\"button\">\n");
      out.write("									<i class=\"fas fa-xmark me-1\"></i> Close\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Bootstrap core JS-->\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<!-- Core theme JS-->\n");
      out.write("	<script src=\"js/scripts.js\"></script>\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("	<!-- * *                               SB Forms JS                               * *-->\n");
      out.write("	<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("	<script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensaje }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
