//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea7_GuiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string IdCliente { get; set; }
        public string NomCliente { get; set; }
        public string DirCliente { get; set; }
        public string idpais { get; set; }
        public string fonoCliente { get; set; }
    
        public virtual paises paises { get; set; }
    }
}
