/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-21 04:06:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fragmetos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comentario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	<section class=\"page-section bg-light\" id=\"team\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"text-center\">\n");
      out.write("				<h2 class=\"section-heading text-uppercase\">Comentarios de clientes</h2>\n");
      out.write("				<h3 class=\"section-subheading text-muted\">\"Desde mi punto de vista, creo que....</h3>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-4\">\n");
      out.write("					<div class=\"team-member\">\n");
      out.write("						<img class=\"mx-auto rounded-circle\" src=\"assets/img/team/1.jpg\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("						<h4>Parveen Anand</h4>\n");
      out.write("						<p class=\"text-muted\">ExploraPerú hizo de mi viaje una experiencia inolvidable, todo estuvo perfectamente organizado.</p>\n");
      out.write("						<a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Parveen Anand Twitter Profile\"><i\n");
      out.write("							class=\"fab fa-twitter\"></i></a>\n");
      out.write("							 <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Parveen Anand Facebook Profile\"><i\n");
      out.write("							class=\"fab fa-facebook-f\"></i></a> <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Parveen Anand LinkedIn Profile\"><i\n");
      out.write("							class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-lg-4\">\n");
      out.write("					<div class=\"team-member\">\n");
      out.write("						<img class=\"mx-auto rounded-circle\" src=\"assets/img/team/2.jpg\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("						<h4>Diana Petersen</h4>\n");
      out.write("						<p class=\"text-muted\">Me encantó la atención personalizada, se nota que conocen y aman el Perú.</p>\n");
      out.write("						<a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Diana Petersen Twitter Profile\"><i\n");
      out.write("							class=\"fab fa-twitter\"></i></a> <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Diana Petersen Facebook Profile\"><i\n");
      out.write("							class=\"fab fa-facebook-f\"></i></a> <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Diana Petersen LinkedIn Profile\"><i\n");
      out.write("							class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-lg-4\">\n");
      out.write("					<div class=\"team-member\">\n");
      out.write("						<img class=\"mx-auto rounded-circle\" src=\"assets/img/team/3.jpg\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("						<h4>Larry Parker</h4>\n");
      out.write("						<p class=\"text-muted\">Gracias a ExploraPerú descubrí lugares que no sabía que existían, ¡100% recomendado!</p>\n");
      out.write("						<a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Larry Parker Twitter Profile\"><i\n");
      out.write("							class=\"fab fa-twitter\"></i></a> <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Larry Parker Facebook Profile\"><i\n");
      out.write("							class=\"fab fa-facebook-f\"></i></a> <a\n");
      out.write("							class=\"btn btn-dark btn-social mx-2\" href=\"#!\"\n");
      out.write("							aria-label=\"Larry Parker LinkedIn Profile\"><i\n");
      out.write("							class=\"fab fa-linkedin-in\"></i></a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-8 mx-auto text-center\">\n");
      out.write("					<p class=\"large text-muted\">Descubre Perú, donde cada paisaje cuenta una historia y cada experiencia se convierte en un recuerdo inolvidable. ¡Atrévete a explorar la magia que te espera!</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
