//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaMVC4_EntityWithSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.pedidoscabe = new HashSet<pedidoscabe>();
        }
    
        public int IdEmpleado { get; set; }
        public string ApeEmpleado { get; set; }
        public string NomEmpleado { get; set; }
        public System.DateTime FecNac { get; set; }
        public string DirEmpleado { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public string fonoEmpleado { get; set; }
        public Nullable<int> idCargo { get; set; }
        public System.DateTime FecContrata { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Distritos Distritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoscabe> pedidoscabe { get; set; }
    }
}
