//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea6_GuiaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NegociosEntities1 : DbContext
    {
        public NegociosEntities1()
            : base("name=NegociosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Distritos> Distritos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<pedidoscabe> pedidoscabe { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<pedidosdeta> pedidosdeta { get; set; }
    
        public virtual ObjectResult<USP_PRODUCTOlISTAR_Result> USP_PRODUCTOlISTAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_PRODUCTOlISTAR_Result>("USP_PRODUCTOlISTAR");
        }
    }
}
