

CREATE TYPE FECHA
FROM DATETIME NOT NULL
GO

EXEC SP_ADDTYPE EDAD, 'CHAR (2)','NULL'
GO

EXEC sp_addtype fax, 'varchar (24)', 'NULL'

CREATE TABLE PRUEBA(
 AL_EDAD EDAD,
 FECHA FECHA,
 FAX FAX
)

SELECT *FROM PRUEBA


--CREACION DE PARTICIONES FUNCIONALES
CREATE PARTITION FUNCTION PF_IDX100(CHAR(4))
AS RANGE RIGHT
FOR VALUES('100','200')

--CREACION DE LOS FILEGROUPS
ALTER DATABASE VENTAS2017
ADD FILEGROUP ID_MENOR

ALTER DATABASE VENTAS2017
ADD FILEGROUP ID_MEDIO

ALTER DATABASE VENTAS2017
ADD FILEGROUP ID_MAYOR

--CREAR NDF CON LOS FILEGROUP

ALTER DATABASE VENTAS2017
ADD FILE(
NAME=ID_MENOR,
FILENAME='C:\MDF_NDF_LDF\ID_MENOR.NDF'
)TO FILEGROUP ID_MENOR
GO

ALTER DATABASE VENTAS2017
ADD FILE(
NAME='ID_MEDIO',
FILENAME='C:\MDF_NDF_LDF\ID_MEDIO.NDF'
)TO FILEGROUP ID_MEDIO

ALTER DATABASE VENTAS2017
ADD FILE(
NAME='ID_MAYOR',
FILENAME='C:\MDF_NDF_LDF\ID_MAYOR.NDF'
)TO FILEGROUP ID_MAYOR


--CREAMIENTO DE UN SQUEMA PARA LAS PARTICIONES
CREATE PARTITION SCHEME PS_IDX100 AS PARTITION PF_IDX100
TO (ID_MENOR, ID_MEDIO, ID_MAYOR)
GO




-- Crear tabla
CREATE TABLE ESTUDIANTE (
    ID CHAR(4) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(40),
    APELLIDO VARCHAR(40),
    MA_COSTO SMALLINT
)ON PS_IDX100(ID)

-- Insertar 300 registros usando una CTE con IDs secuenciales
WITH Numbers AS (
    SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS Number
    FROM master.dbo.spt_values -- Esta tabla tiene más de 100 filas por defecto
)
INSERT INTO ESTUDIANTE (ID, NOMBRE, APELLIDO, MA_COSTO)
SELECT 
    CAST(Number AS CHAR(4)) AS ID, -- IDs secuenciales como '1', '2', ..., '300'
    'Nombre' + CAST(Number AS VARCHAR(3)), 
    'Apellido' + CAST(Number AS VARCHAR(3)),
    ABS(CHECKSUM(NEWID()) % 100) -- Genera un número aleatorio entre 0 y 99
FROM Numbers
WHERE Number <= 300;
GO




SELECT*,$PARTITION.PF_IDX100(ID) AS [PARTITION]
FROM ESTUDIANTE AS E



----------------------------------------------
--CREACION DE OTRA TABLA PARTICIONADA

CREATE PARTITION FUNCTION PF_REGISTRO(CHAR(2))
AS RANGE LEFT
FOR VALUES(10,20,30)

ALTER DATABASE VENTAS2017
ADD FILEGROUP FL_10

ALTER DATABASE VENTAS2017
ADD FILEGROUP FL_20

ALTER DATABASE VENTAS2017
ADD FILEGROUP FL_30

ALTER DATABASE VENTAS2017
ADD FILEGROUP FL_40

ALTER DATABASE VENTAS2017
ADD FILE(
  NAME=FL_10,
  FILENAME='C:\BD_PERSONALIZADO\FL_10.NDF'
)TO FILEGROUP FL_10

ALTER DATABASE VENTAS2017
ADD FILE(
  NAME=FL_20,
  FILENAME='C:\BD_PERSONALIZADO\FL_20.NDF'
)TO FILEGROUP FL_20

ALTER DATABASE VENTAS2017
ADD FILE(
  NAME=FL_30,
  FILENAME='C:\BD_PERSONALIZADO\FL_30.NDF'
)TO FILEGROUP FL_30

ALTER DATABASE VENTAS2017
ADD FILE(
  NAME=FL_40,
  FILENAME='C:\BD_PERSONALIZADO\FL_40.NDF'
)TO FILEGROUP FL_40

CREATE PARTITION SCHEME PS_REGISTROS
AS PARTITION PF_REGISTRO
TO(FL_10,FL_20,FL_30,FL_40)
GO

CREATE TABLE PRUEBITA_1
(
   ID CHAR(2) NOT NULL,
   NOMBRE VARCHAR(50)
)ON PS_REGISTROS(ID)


INSERT INTO PRUEBITA_1(ID,NOMBRE)
VALUES 
(1,'JOSE'),
(11,'MARIA'),
(21,'ARIADNA'),
(31,'NAYELI')

SELECT*FROM PRUEBITA_1


SELECT * ,$PARTITION.PF_REGISTRO(ID) AS [FILE]
FROM PRUEBITA_1