use master

create database PRUEBA2
ON(
   NAME="PRUBEA2",
   FILENAME='C:\BD_PERSONALIZADO\PRUEBA2.MDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
),(
   NAME="PRUBEA2_NDF",
   FILENAME='C:\BD_PERSONALIZADO\PRUEBA2.NDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
) LOG ON(
   NAME="PRUBEA2_LDF",
   FILENAME='C:\BD_PERSONALIZADO\PRUEBA2.LDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
)

USE PRUEBA2


ALTER DATABASE PRUEBA2 ADD FILEGROUP DATA_1
ALTER DATABASE PRUEBA2 ADD FILEGROUP DATA_2

ALTER DATABASE PRUEBA2 
ADD FILE (
   NAME='DATA1',
   FILENAME='C:\BD_PERSONALIZADO\DATA1PRUBA2.NDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
)TO FILEGROUP DATA_1

ALTER DATABASE PRUEBA2 
ADD FILE (
   NAME='DATA2',
   FILENAME='C:\BD_PERSONALIZADO\DATA2PRUBA2.NDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
)TO FILEGROUP DATA_2



ALTER DATABASE PRUEBA2
MODIFY FILE(
NAME='DATA2',
FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\DATA2PRUBA2.NDF'
)


EXEC sp_addtype TELEFONO ,'VARCHAR(9)','NOT NULL'

CREATE TABLE COSA1(
  TFONO TELEFONO
)


ALTER TABLE   COSA1   
ADD NOMBRE VARCHAR(20) NOT NULL

ALTER TABLE COSA1
ALTER COLUMN TFONO VARCHAR(10) NOT NULL

ALTER TABLE COSA1
DROP COLUMN TFONO



--TABLAS PARTICIONADAS

CREATE PARTITION FUNCTION FT_NUMEROS(INT)
AS RANGE LEFT
FOR Values('10','20')
GO

ALTER DATABASE PRUEBA2 ADD FILEGROUP NUMERO1
ALTER DATABASE PRUEBA2 ADD FILEGROUP NUMERO2
ALTER DATABASE PRUEBA2 ADD FILEGROUP NUMERO3

ALTER DATABASE PRUEBA2
ADD FILE(
   NAME='NUMERO1',
   FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\NUMERO1.NDF'
)TO FILEGROUP NUMERO1

ALTER DATABASE PRUEBA2
ADD FILE(
   NAME='NUMERO2',
   FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\NUMERO2.NDF'
)TO FILEGROUP NUMERO2

ALTER DATABASE PRUEBA2
ADD FILE(
   NAME='NUMERO3',
   FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\NUMERO3.NDF'
)TO FILEGROUP NUMERO3



CREATE PARTITION SCHEME PS_NUMERO AS PARTITION FT_NUMEROS
TO(NUMERO1,NUMERO2,NUMERO3)

CREATE TABLE NUMERONCIO(
   NUMERO INT NOT NULL
) ON PS_NUMERO(NUMERO)

INSERT INTO NUMERONCIO(NUMERO)
VALUES (1),(21),(12),(32)


SELECT*,$PARTITION.FT_NUMEROS(NUMERO) AS [PARTITION] FROM NUMERONCIO



--CREATE NUEVA PARTITION

CREATE PARTITION FUNCTION PF_ID(CHAR(2))
AS RANGE RIGHT
FOR VALUES(10)

ALTER DATABASE PRUEBA2 ADD FILEGROUP ID1
ALTER DATABASE PRUEBA2 ADD FILEGROUP ID2

ALTER DATABASE PRUEBA2 
ADD FILE(
   NAME=ID1,
   FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\ID1.NDF'
)TO FILEGROUP ID1

ALTER DATABASE PRUEBA2 
ADD FILE(
   NAME=ID2,
   FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\ID2.NDF'
)TO FILEGROUP ID2

CREATE PARTITION SCHEME PS_ID AS PARTITION PF_ID
TO(ID1,ID2)


CREATE TABLE ID(
   ID CHAR(2),
   NOMBRE VARCHAR(10)
)ON PS_ID(ID)

INSERT INTO ID VALUES ('01','JOSE')
INSERT INTO ID VALUES ('55','MARIA')

SELECT*,$PARTITION.PF_ID(ID) AS ['PARTITION'] FROM ID 


CREATE TABLE PERSONA
(NOMBRE VARCHAR(10),
 NUMERO INT,
 IDPERSONA CHAR(2)
 PRIMARY KEY(IDPERSONA)
)

CREATE TABLE EMPLEADO(
 IDEMPLEADO CHAR(2),
 IDPERSONA CHAR(2),
 DESCRIPCION VARCHAR(23),
 PRIMARY KEY(IDEMPLEADO),
 FOREIGN KEY(IDPERSONA)REFERENCES PERSONA
)

ALTER TABLE PERSONA 
ADD CONSTRAINT DF_NUMERO DEFAULT('99999999') FOR NUMERO

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_ID CHECK(IDEMPLEADO>10) 

ALTER TABLE PERSONA
ADD CONSTRAINT UQ_NUMERO UNIQUE(NUMERO)


INSERT INTO PERSONA (NOMBRE,NUMERO,IDPERSONA)VALUES
('AOSE',9750426,51)

INSERT INTO PERSONA (NOMBRE , IDPERSONA)
VALUES ('ESPINOZA',01)

 SELECT* FROM PERSONA


 CREATE  INDEX INDEX_NAME
 ON PERSONA(NOMBRE)
 INCLUDE(NUMERO,IDPERSONA)

 DROP INDEX INDEX_NAME ON PERSONA