use master
CREATE DATABASE CIBERTEC
ON PRIMARY(
   NAME='CIBERTEC',
   FILENAME='C:\BD_PERSONALIZADO\CIBERTEC.MDF',
   SIZE=10MB,
   MAXSIZE=UNLIMITED
)	
LOG ON(
   NAME='CIBERTECLOG',
   FILENAME='C:\BD_PERSONALIZADO\CIBERTECLOG.LDF',
   MAXSIZE=500MB,
   FILEGROWTH=5MB
)

SP_HELPDB CIBERTEC
GO


ALTER DATABASE CIBERTEC ADD FILEGROUP DATA_1
ALTER DATABASE CIBERTEC ADD FILEGROUP DATA_2
GO

ALTER DATABASE CIBERTEC 
ADD FILE(
   NAME='DATA_1',
   FILENAME='C:\BD_PERSONALIZADO\DATA_1.NDF',
   SIZE=1MB,	
   MAXSIZE=1MB,
   FILEGROWTH=1MB
)TO FILEGROUP DATA_1
GO

ALTER DATABASE CIBERTEC 
ADD FILE(
   NAME='DATA_2',
   FILENAME='C:\BD_PERSONALIZADO\DATA_2.NDF',
   SIZE=1MB,
   MAXSIZE=10MB,
   FILEGROWTH=1MB
)TO FILEGROUP DATA_2
GO


--ALTERAR LOS DATOS DE LOS ARCHIVOS DE LAS BASE DE DATOS

ALTER DATABASE CIBERTEC
MODIFY FILE(
NAME= DATA_2,
SIZE= 10MB,
FILEGROWTH=15%
)
SP_HELPDB CIBERTEC


--CAMBIAR DE UBICACION AL ARCHIVO DE LA BASE DE DATOS
ALTER DATABASE CIBERTEC
MODIFY FILE(
NAME=CIBERTEC,
FILENAME='C:\BD_PERSONALIZADO\NUEVA_UBICACION\CIBERTEC.MDF'
)
